name: eagle_cars
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts:
  go_router:
  loader_overlay:
  flutter_svg: ^2.0.10+1
  flutter_custom_clippers: ^2.1.0
  smooth_page_indicator: ^1.2.0+3
  flutter_otp_text_field: ^1.2.0
  provider: ^6.1.2
  device_preview: ^1.2.0
  connectivity_plus: ^4.0.1
  geolocator: ^13.0.1
  permission_handler:
  google_maps_flutter: ^2.9.0
  flutter_dash: ^1.0.0
  cached_network_image: ^3.4.1
  geocoding: ^3.0.0
  http: ^1.2.2 
  flutter_polyline_points: ^2.1.0
  image_picker: ^1.1.2
  smooth_star_rating_null_safety: ^1.0.4+2
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 23
  adaptive_icon_background: "#00FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

